# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7771d2f85ce810c480ceeb9a698b1d2b3cb8ccefbf2831a1f17b055e5e38e5c2c711daf4d8c9786bf2b58e4598e8150bcd0fd95bfc4bc15e390244144272b84

test:
  secret_key_base: 8954c56499ea6f84b889c1ec31faee03f881436a0b38c8f2d0ec5b6aba9c12b3f9c4360abaa13a35628c5fc4e967347d81fa658ebbb0f333f06dd6b21837c5a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
